services:
    db:
        container_name: gameyou_db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD : 123456
            MYSQL_DATABASE: gamyou_db
        volumes:
            - db_volumes:/var/lib/mysql
        ports:
            - 3307:3306
volumes:
    db_volumes: